### ISSUE TITLE
Allow to customize the default action

### ISSUE THREAD

**Issue by chmp** [chmp/cargo-wop#11]
Per default `cargo wop script.rs` runs the script. For libraries building them would be the more reasonable choice. Maybe add a custom key to the manifest:

```toml
[cargo-wop]
default-action = ["build", "--target", "wasm32-unknown-unknown"]
```

This would make the current default action equivalent to

```toml
[cargo-wop]
default-action = ["run", "--release"]
```

This should only apply to certain commands and trigger the normal cargo-wop rules (like filtering or copying build artifacts).
